---
title: "processingsensitivityoutput"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(RHESSysIOinR)
```

```{r readinsen}

# list the variables that were output from sensitivity analysis 
# these must be file names generated by run_rhessys
var_names=c("lai","trans","evap", "streamflow")

path="sim/out/allsim"
initial_date=ymd("1985-10-1")
parameter_file="sim/out/sen_parameter_sets.csv"

# readin results from sensitivity analysis
res = readin_rhessys_output_cal(var_names, path, initial_date, num_canopies = 1, parameter_file=parameter_file)
# create a string of parameters
parnames = names(select(res, -var_type, -dates, -canopy_layer, -value))
parvalues = unique(res[,parnames])
# make some dates
res$year = year(res$dates)
res$month = month(res$dates)
res$day = day(res$dates)
res$yd = yday(res$dates)
res$wyd = cal.wyd(res)
res$wy = ifelse(as.numeric(res$month) >= 10, res$year+1, res$year)


# make some plots
# first show density of all variable
ggplot(res, aes(value))+geom_density()+facet_wrap(~var_type, scales="free")
parameter_file=read.csv(parameter_file, header=T)

# now look at sensitivity of a particular variable to a parameter
ggplot(subset(res,var_type=="lai"), aes(as.factor(sim.defs.7conifer.def.epc.proj_sla), value))+geom_boxplot()
# make prettier
ggplot(subset(res,var_type=="lai"), aes(as.factor(round(sim.defs.7conifer.def.epc.proj_sla,1)), value))+geom_boxplot()+labs(y="LAI", x="conifer proj SLA")
# multiple parameters
# not so interesting unless you bin the parameters and have lots of simulations
ggplot(subset(res,var_type=="lai"), aes(x=as.factor(round(sim.defs.7conifer.def.epc.proj_sla,0)), y=value, fill=as.factor(round(sim.defs.7conifer.def.epc.leaf_turnover,1))))+geom_boxplot(position="dodge")+labs(y="LAI", x="conifer proj SLA")

# time series
ggplot(subset(res, var_type=="trans"), aes(x=dates, y=value, col=run))+geom_line()+labs(y="Trans (mm/day)")
ggplot(subset(res, var_type=="trans" & wy < 1988), aes(x=dates, y=value, col=run))+geom_line()+labs(y="Trans (mm/day)")



# aggregate
res_wy = res %>% group_by(run, var_type, wy) %>% summarize(max=max(value), sum=sum(value))
# get parameters back
res_wy = left_join(res_wy, parvalues)


ggplot(subset(res_wy, var_type=="trans"), aes(x=run, y=sum))+geom_boxplot()+
  labs(y="Annual Transpiration", x="scenario")

ggplot(subset(res_wy, var_type=="streamflow"), aes(x=as.factor(round(k)), y=max))+geom_boxplot()+
  labs(y="Max Annual FLow", x="K ")

```

